### ISSUE TITLE
error in IDE Arduino 1.5.6-r2

### ISSUE THREAD

**Issue by dyh** [Seeed-Studio/Grove_Serial_Camera_Kit#1]
# include <SPI.h>

please insert "#include <SPI.h>" into the code of <<SerialCameral_DemoCode_CJ_OV528.ino>>

it works fine....
## error: 

C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp: In function 'void spiSend(uint8_t)':
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp:35: error: 'SPI' was not declared in this scope
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp: In function 'uint8_t spiRec()':
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp:44: error: 'SPI' was not declared in this scope
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp: In member function 'uint8_t Sd2Card::init(uint8_t, uint8_t)':
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp:251: error: 'SPI' was not declared in this scope
C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp: In member function 'uint8_t Sd2Card::setSckRate(uint8_t)':

**Comment by ghost** [comment]
Add a line #include <SPI.h>
