### ISSUE TITLE
problem with seeduino 

### ISSUE THREAD

**Issue by pesengineeringclub** [Seeed-Studio/Grove_Serial_Camera_Kit#10]
hi i attached the shield on arduino uno it works ok ,but when i put it on seeduino lora gps version i get nothing ? and also i get this error

WARNING: library SPI claims to run on (samd) architecture(s) and may be incompatible with your current board which runs on (Seeeduino_SAMD) architecture(s). 

any ideas ?

**Comment by ghost** [comment]
I also experiencing the same problem, could someone please help with this issue ?
