### ISSUE TITLE
Resolution is very LOW.

### ISSUE THREAD

**Issue by SiNcSaD** [Seeed-Studio/Grove_Serial_Camera_Kit#5]
I used to your Demo code,but have a problem.

The Photo's Resolution is very LOW !!!

and picTotalLen Mostly in 7xxx to 12xxx 

I also have to replace the camera lens.

How do I solve it.

![pic00](https://cloud.githubusercontent.com/assets/17000388/14934613/fda0ef42-0ee8-11e6-8b45-4b9551b3832d.JPG)

**Comment by KillingJacky** [comment]
The length seems to be in valid range. Problem maybe lies in focal depth.
